
# This file contains the deployment configuration for Headlamp as helm values, a web-based Kubernetes dashboard.

config:
  pluginsDir: "/headlamp/plugins"
  # -- Headlamp plugins directory

# init containers
initContainers:
- name: kubevirt-plugin
  image: docker.io/praveen21b/kubevirt-plugin:v0.0.1-beta3
  command:
  - "/bin/sh"
  - "-c"
  args:
  - cp -r /plugins/kubevirt/* /headlamp/plugins/kubevirt/
  volumeMounts:
  - name: plugin-volume
    mountPath: /headlamp/plugins/kubevirt


# -- Headlamp containers volume mounts
volumeMounts:
- name: plugin-volume
  mountPath: /headlamp/plugins/kubevirt

# -- Headlamp pod's volumes
volumes:
- name: plugin-volume
  emptyDir: {}